/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import blockchain_assignment.Blockchain_Assignment;
import controller.DistributorController;
import controller.HealthcareProviderController;
import controller.ManufacturerController;
import java.io.File;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;
import model.User;
import util.MyKeyPair;

/**
 *
 * @author vinie
 */
public class RegistrationFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationFrame
     */
    private static HealthcareProviderController healthcareProviderController;
    private static ManufacturerController manufacturerController;
    private static DistributorController distributorController;

    public RegistrationFrame(ManufacturerController mc, DistributorController dc, HealthcareProviderController hpc) {
        initComponents();
        manufacturerController = mc;
        healthcareProviderController = hpc;
        distributorController = dc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


//    private String generateID(String role) {    
    private String generateID(String role, String filePath) {

        // Read the last ID from the file
        String lastID = getLastID(role, filePath);

        // Generate the new ID based on the last ID
        String newID;
        if (lastID == null || lastID.isEmpty()) {
            newID = role.substring(0, 1) + "1";
        } else {
            int num = Integer.parseInt(lastID.substring(1)) + 1;
            newID = role.substring(0, 1) + num;
        }

        return newID;
    }

    private String getLastID(String role, String filePath) {
        File file = new File(filePath);
        if (!file.exists()) {
            return null;
        }

        try (Scanner scanner = new Scanner(file)) {
            String lastID = null;
            while (scanner.hasNextLine()) {
                String line = scanner.nextLine();
                String[] parts = line.split(",");
                if (parts.length > 0) {
                    lastID = parts[0];
                }
            }
            return lastID;
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error reading file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRapidCar3 = new javax.swing.JLabel();
        txtCName = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txtCContact = new javax.swing.JTextField();
        txtCCode = new javax.swing.JTextField();
        btnRegister = new javax.swing.JButton();
        comRegisterAs = new javax.swing.JComboBox<>();
        jLabel45 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtCPass = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRapidCar3.setBackground(new java.awt.Color(0, 204, 204));
        lblRapidCar3.setFont(new java.awt.Font("Poppins Medium", 3, 36)); // NOI18N
        lblRapidCar3.setForeground(new java.awt.Color(0, 204, 204));
        lblRapidCar3.setText("Registration");

        txtCName.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        txtCName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCName.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        txtCName.setPreferredSize(new java.awt.Dimension(21, 28));
        txtCName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCNameActionPerformed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel42.setText("Company Name: ");

        jLabel43.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel43.setText("Company Contact: ");

        jLabel44.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel44.setText("Company Registration Code: ");

        txtCContact.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        txtCContact.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCContact.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        txtCContact.setPreferredSize(new java.awt.Dimension(21, 28));
        txtCContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCContactActionPerformed(evt);
            }
        });

        txtCCode.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        txtCCode.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCCode.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        txtCCode.setPreferredSize(new java.awt.Dimension(21, 28));
        txtCCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCCodeActionPerformed(evt);
            }
        });

        btnRegister.setBackground(new java.awt.Color(0, 204, 204));
        btnRegister.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register");
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegisterMouseExited(evt);
            }
        });
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });


        comRegisterAs.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manufacturer", "Distributor", "HealthcareProvider" }));
        comRegisterAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comRegisterAsActionPerformed(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel45.setText("Password:");

        btnLogin.setBackground(new java.awt.Color(0, 204, 204));
        btnLogin.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        txtCPass.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        txtCPass.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        txtCPass.setPreferredSize(new java.awt.Dimension(21, 28));
        txtCPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPassActionPerformed(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel46.setText("Register As: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(lblRapidCar3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel44, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel43)
                                    .addComponent(jLabel42)
                                    .addComponent(jLabel45))
                                .addComponent(jLabel46))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(comRegisterAs, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCContact, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .addComponent(txtCCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                                .addComponent(txtCName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCPass, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblRapidCar3)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel42)
                            .addComponent(txtCName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel43)
                            .addComponent(txtCContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(txtCCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(comRegisterAs, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel46))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCNameActionPerformed

    private void txtCContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCContactActionPerformed

    private void txtCCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCCodeActionPerformed

    private void btnRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterMouseExited

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed

        try {
            String name = txtCName.getText();
            String contact = txtCContact.getText();
            String registrationCode = txtCCode.getText(); // Assuming this is the company registration code
            String role = (String) comRegisterAs.getSelectedItem();
            String password = txtCPass.getText(); // Get the password input

            User u = null;
            
            if (role.equals("Manufacturer")) {
                u = manufacturerController.createNewUser(name, registrationCode, password, contact);
            } else if (role.equals("HealthcareProvider")) {
                u = healthcareProviderController.createNewUser(name, registrationCode, password, contact);
            } else if (role.equals("Distributor")) {
                u = distributorController.createNewUser(name, registrationCode, password, contact);
            }

            // Generate keypair
            MyKeyPair.create();
            // Store private key
            MyKeyPair.put(MyKeyPair.getPrivateKey().getEncoded(), u.getPrivateKeyPath());
            // Store public key
            MyKeyPair.put(MyKeyPair.getPublicKey().getEncoded(), u.getPublicKeyPath());

            JOptionPane.showMessageDialog(this, "Registration successful! Your ID is: " + u.getID() + ". Use this ID for login.");
        } catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error writing to file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void comRegisterAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comRegisterAsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comRegisterAsActionPerformed

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginMouseExited

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        LoginMenu loginf = new LoginMenu(Blockchain_Assignment.manufacturerController,Blockchain_Assignment.distributorController,  Blockchain_Assignment.healthcareProviderController);
        loginf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtCPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationFrame(manufacturerController, distributorController, healthcareProviderController).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<String> comRegisterAs;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel lblRapidCar3;
    private javax.swing.JTextField txtCCode;
    private javax.swing.JTextField txtCContact;
    private javax.swing.JTextField txtCName;
    private javax.swing.JTextField txtCPass;
    // End of variables declaration//GEN-END:variables
}
