/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import blockchain_assignment.Blockchain_Assignment;
import java.security.Key;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;
import util.Block;
import util.Blockchain;
import util.RandomSecretKey;
import util.Symmetric;
import util.TransactionCollection;

/**
 *
 * @author Yuan
 */
public class TrackTraceFrame extends javax.swing.JFrame {

    private static ArrayList<String> transactionArray;
    private static HashMap<String, String> batchCodeToUPCHashMap;
    private static ArrayList<String> allProduct;
    private static HashMap<String, String> batchHashMap;
    private static HashMap<String, String> batchCodeToManufactuerHashMap;
    private static ArrayList<String> allDistributor;
    private static ArrayList<String> allHealthcareProvider;

    /**
     * Creates new form LoginMenu
     */
    public TrackTraceFrame() {

        transactionArray = new ArrayList<>();
        batchCodeToUPCHashMap = new HashMap<>();
        allProduct = new ArrayList<>();
        batchHashMap = new HashMap<>();
        batchCodeToManufactuerHashMap = new HashMap<>();
        allDistributor = new ArrayList<>();
        allHealthcareProvider = new ArrayList<>();
        initComponents();
        loadAllTransaction();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void loadTransactionResultTable(String batchNumber, String batchTransaction) {
        DefaultTableModel transactionResultTableModel = (DefaultTableModel) transactionResultTable.getModel();
        transactionResultTableModel.setRowCount(0);

        // Load Batch
        String[] batchTransactionInfo = batchTransaction.split("\\|");
        String sender = batchTransactionInfo[1];
        String addedDate = batchTransactionInfo[9];

        transactionResultTableModel.addRow(new Object[]{addedDate, "This batch was added", sender, "[recorded in blockchain]"});

        // Load Manufacturer to Distributor
        for (String d : allDistributor) {
            String[] dInfo = d.split("\\|");
            String dBatchNumber = dInfo[0];
            String receiver = dInfo[1];
            String sender2 = dInfo[5];
            String addedDate2 = dInfo[6];

            if (dBatchNumber.equals(batchNumber)) {
                transactionResultTableModel.addRow(new Object[]{addedDate2, "The batch was distributed", sender2, receiver});
            }
        }

        // Load Distributor to Healthcare Provider
        for (String hp : allHealthcareProvider) {
            String[] dInfo = hp.split("\\|");
            String hpBatchNumber = dInfo[0];
            String receiver = dInfo[1];
            String sender3 = dInfo[5];
            String addedDate3 = dInfo[6];

            if (hpBatchNumber.equals(batchNumber)) {
                transactionResultTableModel.addRow(new Object[]{addedDate3, "The batch was distributed", sender3, receiver});
            }
        }
    }

    private void loadDistributor(String batchNumber) {

        DefaultTableModel distributorTableModel = (DefaultTableModel) distributorTable.getModel();
        for (String d : allDistributor) {
            String[] dInfo = d.split("\\|");
            String dBatchNumber = dInfo[0];

            String dName = dInfo[2];
            String dContact = dInfo[3];
            String dCode = dInfo[4];

            if (dBatchNumber.equals(batchNumber)) {
                distributorTableModel.addRow(new Object[]{dName, dContact, dCode});
            }
        }
    }

    private void loadHealthcareProvider(String batchNumber) {
        DefaultTableModel healthcareTableModel = (DefaultTableModel) healthcareTable.getModel();
        for (String hp : allHealthcareProvider) {
            String[] hpInfo = hp.split("\\|");
            String hpBatchNumber = hpInfo[0];
            String hpName = hpInfo[2];
            String hpContact = hpInfo[3];
            String hpCode = hpInfo[4];

            if (hpBatchNumber.equals(batchNumber)) {
                healthcareTableModel.addRow(new Object[]{hpName, hpContact, hpCode});
            }
        }
    }

    private void loadProductTable(String upc) {
        DefaultTableModel productTableModel = (DefaultTableModel) productTable.getModel();

        for (String product : allProduct) {
            String[] productInfo = product.split("\\|");
            String upcProduct = productInfo[4];
            if (upcProduct.equals(upc)) {
                productTableModel.addRow(new Object[]{productInfo[2], productInfo[3], productInfo[4]});
            }
        }
    }

    private void loadBatchTable(String batchNumber) {

        DefaultTableModel batchTableModel = (DefaultTableModel) batchTable.getModel();

        String batch = batchHashMap.get(batchNumber);
        String[] batchInfo = batch.split("\\|");

        String batchCode = batchInfo[4];
        String price = batchInfo[5];
        String dateAdded = batchInfo[9];
        String productionDate = batchInfo[7];
        String expiryDate = batchInfo[8];
        String quantity = batchInfo[6];

        batchTableModel.addRow(new Object[]{batchCode, price, dateAdded, productionDate, expiryDate, quantity, "-"});

    }

    private void loadManufacturerTable(String manufacturerInfo) {
        DefaultTableModel manufacturerTableModel = (DefaultTableModel) manufacturerTable.getModel();

        String[] info = manufacturerInfo.split("\\|");
        String name = info[0];
        String contact = info[1];
        String code = info[2];

        manufacturerTableModel.addRow(new Object[]{name, contact, code});
    }

    private void loadAllTransaction() {

        try {
            // Retrieve product information from the blockchain
            Blockchain blockchain = Blockchain.getInstance("src/On_Chain/Blockchain.bin");
            LinkedList<Block> blockchainData = blockchain.get();

            Symmetric symm = new Symmetric();
            Key secretKey = RandomSecretKey.getSecretKey();
            // Flag to check if any product created by the logged-in user is found
            for (Block block : blockchainData) {
                TransactionCollection transactionCollection = block.getTransactionCollection();
                if (transactionCollection != null) {
                    // Assuming TransactionCollection contains a list of products
                    ArrayList<String> transactions = transactionCollection.getTranxList();
                    // Add product info to the table if the user ID matches the logged-in user
                    for (String transaction : transactions) {
                        String decrypted = symm.decrypt(transaction, secretKey);

                        transactionArray.add(decrypted);

                        String[] data = decrypted.split("\\|");
                        String code = data[0];

                        if (code.equals("001")) {
                            allProduct.add(decrypted);
                        } else if (code.equals("002")) {
                            String upc = data[3];
                            String batchNumber = data[4];
                            String manufacturerID = data[1];
                            String manufacturerName = data[10];
                            String manufacturerContact = data[11];
                            String manufacturerCode = data[12];
                            String info = manufacturerName + "|" + manufacturerContact + "|" + manufacturerCode;
                            batchCodeToUPCHashMap.put(batchNumber, upc);
                            batchHashMap.put(batchNumber, decrypted);
                            batchCodeToManufactuerHashMap.put(batchNumber, info);
                        } else if (code.equals("003")) {
                            String distributorID = data[2];
                            String batchNumber = data[4];
                            String distributorName = data[8];
                            String distributorContact = data[9];
                            String distributorCode = data[10];
                            String sender = data[1];
                            String addedDate = data[11];

                            String distributorInfo = batchNumber + "|" + distributorID + "|" + distributorName + "|" + distributorContact + "|" + distributorCode + "|" + sender + "|" + addedDate;
                            allDistributor.add(distributorInfo);
                        } else if (code.equals("004")) {
                            String healthcareProviderID = data[2];
                            String batchNumber = data[4];
                            String healthcareProviderName = data[8];
                            String healthcareProviderContact = data[9];
                            String healthcareProviderCode = data[10];
                            String sender = data[1];
                            String addedDate = data[11];

                            String HealthcareProviderInfo = batchNumber + "|" + healthcareProviderID + "|" + healthcareProviderName + "|" + healthcareProviderContact + "|" + healthcareProviderCode + "|" + sender + "|" + addedDate;
                            allHealthcareProvider.add(HealthcareProviderInfo);
                        }
                    }
                }
            }
        } catch(Exception e){
            e.printStackTrace();
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        batchNumberField = new javax.swing.JTextField();
        lblRapidCar3 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        tabBooking = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane17 = new javax.swing.JScrollPane();
        transactionResultTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        pnlBookRoom4 = new javax.swing.JPanel();
        lblRapidCar11 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        batchTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        pnlBookRoom2 = new javax.swing.JPanel();
        lblRapidCar10 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        pnlBookRoom1 = new javax.swing.JPanel();
        lblRapidCar7 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jScrollPane15 = new javax.swing.JScrollPane();
        manufacturerTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblRapidCar8 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        distributorTable = new javax.swing.JTable();
        pnlBookRoom3 = new javax.swing.JPanel();
        lblRapidCar9 = new javax.swing.JLabel();
        selectedTransactionLabelValue = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        healthcareTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnBackLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        batchNumberField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        batchNumberField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        batchNumberField.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        batchNumberField.setPreferredSize(new java.awt.Dimension(21, 28));
        batchNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchNumberFieldActionPerformed(evt);
            }
        });

        lblRapidCar3.setBackground(new java.awt.Color(0, 204, 204));
        lblRapidCar3.setFont(new java.awt.Font("Poppins Medium", 3, 36)); // NOI18N
        lblRapidCar3.setForeground(new java.awt.Color(0, 204, 204));
        lblRapidCar3.setText("Track and Trace");

        jLabel42.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel42.setText("Batch Number");

        tabBooking.setBackground(new java.awt.Color(0, 204, 204));
        tabBooking.setForeground(new java.awt.Color(255, 255, 255));
        tabBooking.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                tabBookingComponentMoved(evt);
            }
        });

        transactionResultTable.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        transactionResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Transaction Date", "Action", "Sender", "Receiver"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        transactionResultTable.setToolTipText("");
        transactionResultTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionResultTableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transactionResultTableMouseEntered(evt);
            }
        });
        jScrollPane17.setViewportView(transactionResultTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane17)
                .addGap(79, 79, 79))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        tabBooking.addTab("Result", jPanel4);

        pnlBookRoom4.setBackground(new java.awt.Color(227, 235, 238));

        lblRapidCar11.setBackground(new java.awt.Color(0, 204, 204));
        lblRapidCar11.setFont(new java.awt.Font("Poppins Medium", 1, 24)); // NOI18N
        lblRapidCar11.setForeground(new java.awt.Color(0, 204, 204));
        lblRapidCar11.setText("Batch");

        jLabel53.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel53.setText("-");

        batchTable.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        batchTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Batch Number", "Price", "Date Added", "Production Date", "Expiry Date", "Total Quantity", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        batchTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                batchTableMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(batchTable);

        javax.swing.GroupLayout pnlBookRoom4Layout = new javax.swing.GroupLayout(pnlBookRoom4);
        pnlBookRoom4.setLayout(pnlBookRoom4Layout);
        pnlBookRoom4Layout.setHorizontalGroup(
            pnlBookRoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBookRoom4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
            .addGroup(pnlBookRoom4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlBookRoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRapidCar11)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        pnlBookRoom4Layout.setVerticalGroup(
            pnlBookRoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBookRoom4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblRapidCar11)
                .addGap(19, 19, 19)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel53)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 873, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlBookRoom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlBookRoom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        tabBooking.addTab("Batch", jPanel3);

        pnlBookRoom2.setBackground(new java.awt.Color(227, 235, 238));

        lblRapidCar10.setBackground(new java.awt.Color(0, 204, 204));
        lblRapidCar10.setFont(new java.awt.Font("Poppins Medium", 1, 24)); // NOI18N
        lblRapidCar10.setForeground(new java.awt.Color(0, 204, 204));
        lblRapidCar10.setText("Product");

        jLabel52.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel52.setText("-");

        productTable.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Description", "UPC"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productTableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                productTableMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(productTable);

        javax.swing.GroupLayout pnlBookRoom2Layout = new javax.swing.GroupLayout(pnlBookRoom2);
        pnlBookRoom2.setLayout(pnlBookRoom2Layout);
        pnlBookRoom2Layout.setHorizontalGroup(
            pnlBookRoom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBookRoom2Layout.createSequentialGroup()
                .addContainerGap(501, Short.MAX_VALUE)
                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
            .addGroup(pnlBookRoom2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlBookRoom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRapidCar10)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBookRoom2Layout.setVerticalGroup(
            pnlBookRoom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBookRoom2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblRapidCar10)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel52)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 873, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlBookRoom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 365, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlBookRoom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        tabBooking.addTab("Product", jPanel1);

        pnlBookRoom1.setBackground(new java.awt.Color(227, 235, 238));

        lblRapidCar7.setBackground(new java.awt.Color(0, 204, 204));
        lblRapidCar7.setFont(new java.awt.Font("Poppins Medium", 1, 24)); // NOI18N
        lblRapidCar7.setForeground(new java.awt.Color(0, 204, 204));
        lblRapidCar7.setText("Manufacturer");

        jLabel51.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel51.setText("-");

        manufacturerTable.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        manufacturerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Company Name", "Contact Number", "Company Registration Code"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        manufacturerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manufacturerTableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manufacturerTableMouseEntered(evt);
            }
        });
        jScrollPane15.setViewportView(manufacturerTable);

        javax.swing.GroupLayout pnlBookRoom1Layout = new javax.swing.GroupLayout(pnlBookRoom1);
        pnlBookRoom1.setLayout(pnlBookRoom1Layout);
        pnlBookRoom1Layout.setHorizontalGroup(
            pnlBookRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBookRoom1Layout.createSequentialGroup()
                .addContainerGap(485, Short.MAX_VALUE)
                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
            .addGroup(pnlBookRoom1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblRapidCar7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlBookRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlBookRoom1Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(38, Short.MAX_VALUE)))
        );
        pnlBookRoom1Layout.setVerticalGroup(
            pnlBookRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBookRoom1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblRapidCar7)
                .addGap(113, 113, 113)
                .addComponent(jLabel51)
                .addContainerGap(185, Short.MAX_VALUE))
            .addGroup(pnlBookRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlBookRoom1Layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(jScrollPane15, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(66, Short.MAX_VALUE)))
        );

        tabBooking.addTab("Manufacturer", pnlBookRoom1);

        jPanel2.setBackground(new java.awt.Color(227, 235, 238));

        lblRapidCar8.setBackground(new java.awt.Color(0, 204, 204));
        lblRapidCar8.setFont(new java.awt.Font("Poppins Medium", 1, 24)); // NOI18N
        lblRapidCar8.setForeground(new java.awt.Color(0, 204, 204));
        lblRapidCar8.setText("Distributor");

        distributorTable.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        distributorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Company Name", "Contact Number", "Company Registration Code"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        distributorTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                distributorTableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                distributorTableMouseEntered(evt);
            }
        });
        jScrollPane13.setViewportView(distributorTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRapidCar8)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblRapidCar8)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        tabBooking.addTab("Distributor", jPanel2);

        pnlBookRoom3.setBackground(new java.awt.Color(227, 235, 238));

        lblRapidCar9.setBackground(new java.awt.Color(0, 204, 204));
        lblRapidCar9.setFont(new java.awt.Font("Poppins Medium", 1, 24)); // NOI18N
        lblRapidCar9.setForeground(new java.awt.Color(0, 204, 204));
        lblRapidCar9.setText("Healthcare Provider");

        selectedTransactionLabelValue.setText("-");

        healthcareTable.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        healthcareTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Company Name", "Contact Number", "Company Registration Code"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        healthcareTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                healthcareTableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                healthcareTableMouseEntered(evt);
            }
        });
        jScrollPane14.setViewportView(healthcareTable);

        javax.swing.GroupLayout pnlBookRoom3Layout = new javax.swing.GroupLayout(pnlBookRoom3);
        pnlBookRoom3.setLayout(pnlBookRoom3Layout);
        pnlBookRoom3Layout.setHorizontalGroup(
            pnlBookRoom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBookRoom3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlBookRoom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBookRoom3Layout.createSequentialGroup()
                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(selectedTransactionLabelValue, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblRapidCar9))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlBookRoom3Layout.setVerticalGroup(
            pnlBookRoom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBookRoom3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblRapidCar9)
                .addGroup(pnlBookRoom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBookRoom3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                        .addComponent(selectedTransactionLabelValue)
                        .addGap(129, 129, 129))
                    .addGroup(pnlBookRoom3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        tabBooking.addTab("Healthcare Provider", pnlBookRoom3);

        jButton1.setText("Search");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        btnBackLogin.setBackground(new java.awt.Color(255, 153, 102));
        btnBackLogin.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnBackLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnBackLogin.setText("Back");
        btnBackLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackLoginMouseExited(evt);
            }
        });
        btnBackLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(lblRapidCar3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBackLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel42)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(batchNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tabBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRapidCar3)
                    .addComponent(btnBackLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel42)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(batchNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(tabBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void batchNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batchNumberFieldActionPerformed

    private void tabBookingComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabBookingComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tabBookingComponentMoved

    private void batchTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_batchTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_batchTableMouseClicked

    private void productTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productTableMouseClicked

    }//GEN-LAST:event_productTableMouseClicked

    private void productTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productTableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_productTableMouseEntered

    private void distributorTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_distributorTableMouseClicked

    }//GEN-LAST:event_distributorTableMouseClicked

    private void distributorTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_distributorTableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_distributorTableMouseEntered

    private void healthcareTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_healthcareTableMouseClicked

    }//GEN-LAST:event_healthcareTableMouseClicked

    private void healthcareTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_healthcareTableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_healthcareTableMouseEntered

    private void manufacturerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manufacturerTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_manufacturerTableMouseClicked

    private void manufacturerTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manufacturerTableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_manufacturerTableMouseEntered

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String batchCodeInput = batchNumberField.getText();

        if (batchCodeInput.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a batch number", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!batchCodeToUPCHashMap.containsKey(batchCodeInput)) {
            JOptionPane.showMessageDialog(this, "Batch Number not found", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String upc = batchCodeToUPCHashMap.get(batchCodeInput);
        String manufacturerInfo = batchCodeToManufactuerHashMap.get(batchCodeInput);
        String batchTransaction = batchHashMap.get(batchCodeInput);

        loadProductTable(upc);
        loadBatchTable(batchCodeInput);
        loadManufacturerTable(manufacturerInfo);
        loadDistributor(batchCodeInput);
        loadHealthcareProvider(batchCodeInput);
        loadTransactionResultTable(batchCodeInput, batchTransaction);

    }//GEN-LAST:event_jButton1MouseClicked

    private void btnBackLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackLoginMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackLoginMouseExited

    private void btnBackLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackLoginActionPerformed
        this.setVisible(false);
        new LoginMenu(Blockchain_Assignment.manufacturerController, Blockchain_Assignment.distributorController, Blockchain_Assignment.healthcareProviderController).setVisible(true);
    }//GEN-LAST:event_btnBackLoginActionPerformed

    private void transactionResultTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionResultTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_transactionResultTableMouseClicked

    private void transactionResultTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionResultTableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_transactionResultTableMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrackTraceFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrackTraceFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrackTraceFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrackTraceFrame.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrackTraceFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField batchNumberField;
    private javax.swing.JTable batchTable;
    private javax.swing.JButton btnBackLogin;
    private javax.swing.JTable distributorTable;
    private javax.swing.JTable healthcareTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblRapidCar10;
    private javax.swing.JLabel lblRapidCar11;
    private javax.swing.JLabel lblRapidCar3;
    private javax.swing.JLabel lblRapidCar7;
    private javax.swing.JLabel lblRapidCar8;
    private javax.swing.JLabel lblRapidCar9;
    private javax.swing.JTable manufacturerTable;
    private javax.swing.JPanel pnlBookRoom1;
    private javax.swing.JPanel pnlBookRoom2;
    private javax.swing.JPanel pnlBookRoom3;
    private javax.swing.JPanel pnlBookRoom4;
    private javax.swing.JTable productTable;
    private javax.swing.JLabel selectedTransactionLabelValue;
    private javax.swing.JTabbedPane tabBooking;
    private javax.swing.JTable transactionResultTable;
    // End of variables declaration//GEN-END:variables
}
