/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import blockchain_assignment.Blockchain_Assignment;

/**
 *
 * @author vinie
 */
public class TracknTrace extends javax.swing.JFrame {

    /**
     * Creates new form TracknTrace
     */
    public TracknTrace() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnBackLogin = new javax.swing.JButton();
        jLabel52 = new javax.swing.JLabel();
        batchNumberField1 = new javax.swing.JTextField();
        batchNumberField = new javax.swing.JTextField();
        lblRapidCar3 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        tabBooking = new javax.swing.JTabbedPane();
        pnlBookRoom6 = new javax.swing.JPanel();
        selectedTransactionLabelValue2 = new javax.swing.JLabel();
        jScrollPane17 = new javax.swing.JScrollPane();
        healthcareTable2 = new javax.swing.JTable();
        btnViewBatch = new javax.swing.JButton();
        btnViewBatch1 = new javax.swing.JButton();
        btnViewBatch2 = new javax.swing.JButton();
        btnViewBatch3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        pnlBookRoom4 = new javax.swing.JPanel();
        lblRapidCar11 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        pnlBookRoom1 = new javax.swing.JPanel();
        lblRapidCar7 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblRapidCar8 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        distributorTable = new javax.swing.JTable();
        pnlBookRoom3 = new javax.swing.JPanel();
        selectedTransactionLabelValue = new javax.swing.JLabel();
        pnlBookRoom5 = new javax.swing.JPanel();
        lblRapidCar12 = new javax.swing.JLabel();
        selectedTransactionLabelValue1 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        healthcareTable = new javax.swing.JTable();
        jLabel78 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Search");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnBackLogin.setBackground(new java.awt.Color(255, 153, 102));
        btnBackLogin.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnBackLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnBackLogin.setText("Back");
        btnBackLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackLoginMouseExited(evt);
            }
        });
        btnBackLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackLoginActionPerformed(evt);
            }
        });

        jLabel52.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(204, 0, 51));
        jLabel52.setText("Valid Product");

        batchNumberField1.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        batchNumberField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        batchNumberField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        batchNumberField1.setPreferredSize(new java.awt.Dimension(21, 28));
        batchNumberField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchNumberField1ActionPerformed(evt);
            }
        });

        batchNumberField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        batchNumberField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        batchNumberField.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        batchNumberField.setPreferredSize(new java.awt.Dimension(21, 28));
        batchNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batchNumberFieldActionPerformed(evt);
            }
        });

        lblRapidCar3.setBackground(new java.awt.Color(0, 204, 204));
        lblRapidCar3.setFont(new java.awt.Font("Poppins Medium", 3, 36)); // NOI18N
        lblRapidCar3.setForeground(new java.awt.Color(0, 204, 204));
        lblRapidCar3.setText("Track and Trace");

        jLabel42.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel42.setText("Batch Number");

        tabBooking.setBackground(new java.awt.Color(0, 204, 204));
        tabBooking.setForeground(new java.awt.Color(255, 255, 255));
        tabBooking.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                tabBookingComponentMoved(evt);
            }
        });

        pnlBookRoom6.setBackground(new java.awt.Color(227, 235, 238));

        selectedTransactionLabelValue2.setText("-");

        healthcareTable2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        healthcareTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Transaction Date", "Action", "Sender", "Receiver"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        healthcareTable2.setToolTipText("");
        healthcareTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                healthcareTable2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                healthcareTable2MouseEntered(evt);
            }
        });
        jScrollPane17.setViewportView(healthcareTable2);

        btnViewBatch.setBackground(new java.awt.Color(0, 204, 204));
        btnViewBatch.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnViewBatch.setForeground(new java.awt.Color(255, 255, 255));
        btnViewBatch.setText("View Manufacturer");
        btnViewBatch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewBatchMouseExited(evt);
            }
        });
        btnViewBatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBatchActionPerformed(evt);
            }
        });

        btnViewBatch1.setBackground(new java.awt.Color(0, 204, 204));
        btnViewBatch1.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnViewBatch1.setForeground(new java.awt.Color(255, 255, 255));
        btnViewBatch1.setText("View Healthcare Provider");
        btnViewBatch1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewBatch1MouseExited(evt);
            }
        });
        btnViewBatch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBatch1ActionPerformed(evt);
            }
        });

        btnViewBatch2.setBackground(new java.awt.Color(0, 204, 204));
        btnViewBatch2.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnViewBatch2.setForeground(new java.awt.Color(255, 255, 255));
        btnViewBatch2.setText("View Distributor");
        btnViewBatch2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewBatch2MouseExited(evt);
            }
        });
        btnViewBatch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBatch2ActionPerformed(evt);
            }
        });

        btnViewBatch3.setBackground(new java.awt.Color(0, 204, 204));
        btnViewBatch3.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        btnViewBatch3.setForeground(new java.awt.Color(255, 255, 255));
        btnViewBatch3.setText("View Batch Details");
        btnViewBatch3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewBatch3MouseExited(evt);
            }
        });
        btnViewBatch3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBatch3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBookRoom6Layout = new javax.swing.GroupLayout(pnlBookRoom6);
        pnlBookRoom6.setLayout(pnlBookRoom6Layout);
        pnlBookRoom6Layout.setHorizontalGroup(
            pnlBookRoom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBookRoom6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlBookRoom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane17)
                    .addGroup(pnlBookRoom6Layout.createSequentialGroup()
                        .addComponent(btnViewBatch3)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewBatch)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewBatch2)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewBatch1)))
                .addGap(74, 74, 74)
                .addComponent(selectedTransactionLabelValue2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlBookRoom6Layout.setVerticalGroup(
            pnlBookRoom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBookRoom6Layout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addComponent(selectedTransactionLabelValue2)
                .addGap(129, 129, 129))
            .addGroup(pnlBookRoom6Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(pnlBookRoom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewBatch, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewBatch2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewBatch3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewBatch1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabBooking.addTab("Result", pnlBookRoom6);

        pnlBookRoom4.setBackground(new java.awt.Color(227, 235, 238));

        lblRapidCar11.setBackground(new java.awt.Color(0, 204, 204));
        lblRapidCar11.setFont(new java.awt.Font("Poppins Medium", 1, 24)); // NOI18N
        lblRapidCar11.setForeground(new java.awt.Color(0, 204, 204));
        lblRapidCar11.setText("Batch Details");

        jLabel53.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel53.setText("-");

        jLabel63.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel63.setText("Expiry Date");

        jLabel64.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel64.setText("Batch Number");

        jLabel66.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel66.setText("Production Date");

        jLabel67.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel67.setText("Production Quantity");

        jLabel68.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel68.setText("Product Name");

        jLabel69.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel69.setText("Product UPC");

        jLabel70.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel70.setText("Product Description");

        jLabel65.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel65.setText("-");

        jLabel71.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel71.setText("-");

        jLabel72.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel72.setText("-");

        jLabel73.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel73.setText("-");

        jLabel74.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel74.setText("-");

        jLabel75.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel75.setText("-");

        jLabel76.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel76.setText("-");

        javax.swing.GroupLayout pnlBookRoom4Layout = new javax.swing.GroupLayout(pnlBookRoom4);
        pnlBookRoom4.setLayout(pnlBookRoom4Layout);
        pnlBookRoom4Layout.setHorizontalGroup(
            pnlBookRoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBookRoom4Layout.createSequentialGroup()
                .addContainerGap(501, Short.MAX_VALUE)
                .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
            .addGroup(pnlBookRoom4Layout.createSequentialGroup()
                .addGroup(pnlBookRoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBookRoom4Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(pnlBookRoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlBookRoom4Layout.createSequentialGroup()
                                .addComponent(jLabel63)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBookRoom4Layout.createSequentialGroup()
                                .addComponent(jLabel66)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBookRoom4Layout.createSequentialGroup()
                                .addComponent(jLabel67)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlBookRoom4Layout.createSequentialGroup()
                                .addComponent(jLabel64)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBookRoom4Layout.createSequentialGroup()
                                .addComponent(jLabel70)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBookRoom4Layout.createSequentialGroup()
                                .addComponent(jLabel69)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBookRoom4Layout.createSequentialGroup()
                                .addComponent(jLabel68)
                                .addGap(69, 69, 69)
                                .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlBookRoom4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblRapidCar11)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBookRoom4Layout.setVerticalGroup(
            pnlBookRoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBookRoom4Layout.createSequentialGroup()
                .addGroup(pnlBookRoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBookRoom4Layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(jLabel53))
                    .addGroup(pnlBookRoom4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblRapidCar11)
                        .addGap(33, 33, 33)
                        .addGroup(pnlBookRoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel68)
                            .addComponent(jLabel65))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlBookRoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel70)
                            .addComponent(jLabel71))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlBookRoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel69)
                            .addComponent(jLabel72))
                        .addGap(33, 33, 33)
                        .addGroup(pnlBookRoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel64)
                            .addComponent(jLabel73))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlBookRoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel67)
                            .addComponent(jLabel75))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlBookRoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel66)
                            .addComponent(jLabel76))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlBookRoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel63)
                            .addComponent(jLabel74))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 873, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlBookRoom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlBookRoom4, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        tabBooking.addTab("Batch", jPanel3);

        pnlBookRoom1.setBackground(new java.awt.Color(227, 235, 238));

        lblRapidCar7.setBackground(new java.awt.Color(0, 204, 204));
        lblRapidCar7.setFont(new java.awt.Font("Poppins Medium", 1, 24)); // NOI18N
        lblRapidCar7.setForeground(new java.awt.Color(0, 204, 204));
        lblRapidCar7.setText("Manufacturer Details");

        jLabel51.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel51.setText("-");

        jLabel43.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel43.setText("Company Name: ");

        jLabel44.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel44.setText("Company Contact: ");

        jLabel45.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel45.setText("Company Registration Code: ");

        jLabel57.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel57.setText("-");

        jLabel58.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel58.setText("-");

        javax.swing.GroupLayout pnlBookRoom1Layout = new javax.swing.GroupLayout(pnlBookRoom1);
        pnlBookRoom1.setLayout(pnlBookRoom1Layout);
        pnlBookRoom1Layout.setHorizontalGroup(
            pnlBookRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBookRoom1Layout.createSequentialGroup()
                .addGroup(pnlBookRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBookRoom1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblRapidCar7))
                    .addGroup(pnlBookRoom1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(pnlBookRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel43)
                            .addComponent(jLabel44)
                            .addComponent(jLabel45))
                        .addGap(23, 23, 23)
                        .addGroup(pnlBookRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(316, Short.MAX_VALUE))
        );
        pnlBookRoom1Layout.setVerticalGroup(
            pnlBookRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBookRoom1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblRapidCar7)
                .addGap(38, 38, 38)
                .addGroup(pnlBookRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(jLabel51))
                .addGap(31, 31, 31)
                .addGroup(pnlBookRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(jLabel57))
                .addGap(36, 36, 36)
                .addGroup(pnlBookRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(jLabel58))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        tabBooking.addTab("Manufacturer", pnlBookRoom1);

        jPanel2.setBackground(new java.awt.Color(227, 235, 238));

        lblRapidCar8.setBackground(new java.awt.Color(0, 204, 204));
        lblRapidCar8.setFont(new java.awt.Font("Poppins Medium", 1, 24)); // NOI18N
        lblRapidCar8.setForeground(new java.awt.Color(0, 204, 204));
        lblRapidCar8.setText("Distributor Details");

        distributorTable.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        distributorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Company Name", "Contact Number", "Company Registration Code"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        distributorTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                distributorTableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                distributorTableMouseEntered(evt);
            }
        });
        jScrollPane13.setViewportView(distributorTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRapidCar8))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblRapidCar8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        tabBooking.addTab("Distributor", jPanel2);

        pnlBookRoom3.setBackground(new java.awt.Color(227, 235, 238));

        selectedTransactionLabelValue.setText("-");

        pnlBookRoom5.setBackground(new java.awt.Color(227, 235, 238));

        lblRapidCar12.setBackground(new java.awt.Color(0, 204, 204));
        lblRapidCar12.setFont(new java.awt.Font("Poppins Medium", 1, 24)); // NOI18N
        lblRapidCar12.setForeground(new java.awt.Color(0, 204, 204));
        lblRapidCar12.setText("Healthcare Provider Details");

        selectedTransactionLabelValue1.setText("-");

        healthcareTable.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        healthcareTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Company Name", "Contact Number", "Company Registration Code"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        healthcareTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                healthcareTableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                healthcareTableMouseEntered(evt);
            }
        });
        jScrollPane14.setViewportView(healthcareTable);

        javax.swing.GroupLayout pnlBookRoom5Layout = new javax.swing.GroupLayout(pnlBookRoom5);
        pnlBookRoom5.setLayout(pnlBookRoom5Layout);
        pnlBookRoom5Layout.setHorizontalGroup(
            pnlBookRoom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBookRoom5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(pnlBookRoom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBookRoom5Layout.createSequentialGroup()
                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(selectedTransactionLabelValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblRapidCar12, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlBookRoom5Layout.setVerticalGroup(
            pnlBookRoom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBookRoom5Layout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addComponent(selectedTransactionLabelValue1)
                .addGap(129, 129, 129))
            .addGroup(pnlBookRoom5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblRapidCar12)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlBookRoom3Layout = new javax.swing.GroupLayout(pnlBookRoom3);
        pnlBookRoom3.setLayout(pnlBookRoom3Layout);
        pnlBookRoom3Layout.setHorizontalGroup(
            pnlBookRoom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBookRoom3Layout.createSequentialGroup()
                .addGap(837, 837, 837)
                .addComponent(selectedTransactionLabelValue, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlBookRoom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlBookRoom3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlBookRoom5, javax.swing.GroupLayout.PREFERRED_SIZE, 1061, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlBookRoom3Layout.setVerticalGroup(
            pnlBookRoom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBookRoom3Layout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addComponent(selectedTransactionLabelValue)
                .addGap(129, 129, 129))
            .addGroup(pnlBookRoom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlBookRoom3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlBookRoom5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 1, Short.MAX_VALUE)))
        );

        tabBooking.addTab("Healthcare Provider", pnlBookRoom3);

        jLabel78.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel78.setText("Unit Code");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(lblRapidCar3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBackLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(batchNumberField1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel78))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(batchNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel52))
                            .addComponent(jLabel42)))
                    .addComponent(tabBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRapidCar3)
                    .addComponent(btnBackLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(jLabel78))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(batchNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(batchNumberField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52))
                .addGap(30, 30, 30)
                .addComponent(tabBooking, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBackLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackLoginMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackLoginMouseExited

    private void btnBackLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackLoginActionPerformed
        this.setVisible(false);
        new LoginMenu(Blockchain_Assignment.manufacturerController, Blockchain_Assignment.distributorController, Blockchain_Assignment.healthcareProviderController).setVisible(true);
    }//GEN-LAST:event_btnBackLoginActionPerformed

    private void batchNumberField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchNumberField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batchNumberField1ActionPerformed

    private void batchNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batchNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_batchNumberFieldActionPerformed

    private void healthcareTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_healthcareTable2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_healthcareTable2MouseClicked

    private void healthcareTable2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_healthcareTable2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_healthcareTable2MouseEntered

    private void btnViewBatchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewBatchMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewBatchMouseExited

    private void btnViewBatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBatchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewBatchActionPerformed

    private void btnViewBatch1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewBatch1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewBatch1MouseExited

    private void btnViewBatch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBatch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewBatch1ActionPerformed

    private void btnViewBatch2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewBatch2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewBatch2MouseExited

    private void btnViewBatch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBatch2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewBatch2ActionPerformed

    private void btnViewBatch3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewBatch3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewBatch3MouseExited

    private void btnViewBatch3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBatch3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewBatch3ActionPerformed

    private void tabBookingComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabBookingComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tabBookingComponentMoved

    private void distributorTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_distributorTableMouseClicked

    }//GEN-LAST:event_distributorTableMouseClicked

    private void distributorTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_distributorTableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_distributorTableMouseEntered

    private void healthcareTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_healthcareTableMouseClicked

    }//GEN-LAST:event_healthcareTableMouseClicked

    private void healthcareTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_healthcareTableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_healthcareTableMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TracknTrace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TracknTrace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TracknTrace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TracknTrace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TracknTrace().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField batchNumberField;
    private javax.swing.JTextField batchNumberField1;
    private javax.swing.JButton btnBackLogin;
    private javax.swing.JButton btnViewBatch;
    private javax.swing.JButton btnViewBatch1;
    private javax.swing.JButton btnViewBatch2;
    private javax.swing.JButton btnViewBatch3;
    private javax.swing.JTable distributorTable;
    private javax.swing.JTable healthcareTable;
    private javax.swing.JTable healthcareTable2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JLabel lblRapidCar11;
    private javax.swing.JLabel lblRapidCar12;
    private javax.swing.JLabel lblRapidCar3;
    private javax.swing.JLabel lblRapidCar7;
    private javax.swing.JLabel lblRapidCar8;
    private javax.swing.JPanel pnlBookRoom1;
    private javax.swing.JPanel pnlBookRoom3;
    private javax.swing.JPanel pnlBookRoom4;
    private javax.swing.JPanel pnlBookRoom5;
    private javax.swing.JPanel pnlBookRoom6;
    private javax.swing.JLabel selectedTransactionLabelValue;
    private javax.swing.JLabel selectedTransactionLabelValue1;
    private javax.swing.JLabel selectedTransactionLabelValue2;
    private javax.swing.JTabbedPane tabBooking;
    // End of variables declaration//GEN-END:variables
}
